import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
      title: 'Create Next App',
      description: 'Generated by create next app',
};

export default function RootLayout({
      children,
}: {
      children: React.ReactNode;
}) {
      return (
            <html lang="en">
                  <body className="min-h-screen bg-gradient-to-b from-sky-200 to-sky-400">
                        <main>{children}</main>
                  </body>
            </html>
      );
}
