import './globals.css';
import type { Metadata } from 'next';
import Sidebar from './Components/Sidebar';
import Footer from './Components/Footer';

import Today from './today/page';

export const metadata: Metadata = {
      title: 'Clean Weather Forecast',
      description: 'Generated by create next app',
};

export default function RootLayout({
      children,
}: {
      children: React.ReactNode;
}) {
      return (
            <html lang="en">
                  <body className="min-h-screen bg-gradient-to-b from-sky-200 to-sky-300">
                        <Sidebar />
                        {children}
                        <Footer />
                  </body>
            </html>
      );
}
